### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

### ISSUE THREAD

**Issue by stephendonner** [davehunt/raptor-studio#30]
This ($PATH to geckodriver missing) might be something more to document (and if so, are there more-succinct/correct docs than https://www.kenst.com/2016/12/installing-marionette-firefoxdriver-on-mac-osx/?), than to fix, but when I run:

(raptor-studio) bash-3.2$ `pipenv run python studio.py --app Firefox --proxy mitm4 --record --sites desktop-sites.json`

I get the following traceback:

>
Starting record mode!!!
Parsing sites json
Creating recording path: Recordings/mitm4-darwin-firefox-google-search
Starting MitmProxy
/Users/sdonner/raptor-studio/proxy/utils/mitm4.0.4/mitmdump-osx --save-stream-file Recordings/mitm4-darwin-firefox-google-search/mitm4-darwin-firefox-google-search.mp --set websocket=false --scripts /Users/sdonner/raptor-studio/proxy/scripts/inject_deterministic.py --scripts /Users/sdonner/raptor-studio/proxy/scripts/http_protocol_extractor.py
Recording https://www.google.com/search?hl=en&q=barack+obama&cad=h...`

> 
Traceback (most recent call last):
  File "studio.py", line 240, in <module>
    cli()
  File "/Users/sdonner/.local/share/virtualenvs/raptor-studio-nIIebfAe/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sdonner/.local/share/virtualenvs/raptor-studio-nIIebfAe/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sdonner/.local/share/virtualenvs/raptor-studio-nIIebfAe/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sdonner/.local/share/virtualenvs/raptor-studio-nIIebfAe/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "studio.py", line 234, in cli
    mode.recording()
  File "studio.py", line 88, in recording
    app_service.start(site["url"])
  File "/Users/sdonner/raptor-studio/apps/desktop/firefox.py", line 17, in start
    self.driver = Firefox(options=options, firefox_binary=self.binary)
  File "/Users/sdonner/.local/share/virtualenvs/raptor-studio-nIIebfAe/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Users/sdonner/.local/share/virtualenvs/raptor-studio-nIIebfAe/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by stephendonner** [comment]
I'm all set - using the KISS principle, I just added a tiny blurb to the README, in https://github.com/mozilla/raptor-studio/pull/31
